language: objective-c

branches:
  only:
    - master

install:
  - curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec bundle install --without=development integration

before_script:
  - cp .kitchen.travis.yml .kitchen.local.yml

script:
  - chef exec bundle exec rake && chef exec bundle exec kitchen test
