language: objective-c

install:
  - curl -L https://www.opscode.com/chef/install.sh | sudo bash -s -- -P chefdk
  - chef exec berks vendor /tmp/kitchen/cookbooks
  - sudo chef-client -z -c test/client.rb -j test/dna.json
  - chef exec bundle install --without=development

before_script:
  # Pending ENV support in Kitchen's Rake tasks and not just the CLI
  - cp .kitchen.travis.yml .kitchen.local.yml
  - echo -e $DIGITALOCEAN_SSH_KEY_BODY > ~/.ssh/id_rsa

script:
  - chef exec rake && chef exec bundle exec rspec --default-path test/integration/default/serverspec -f d

after_script:

env:
  global:
    # - KITCHEN_LOCAL_YAML=.kitchen.travis.yml
